#!/bin/sh

SERVER=irc.freenode.net
PORT=7000
SSL=1
WAIT_FOR_NS_BEFORE_JOIN=1 # Set to 0 if you don't want to wait for some Nickserv msg before joining channel

nick="haumbotox"
channel=haum
password="PUT YOUR BOT'S PASSWORD HERE"
msg="!spaceapi state toggle"
