#!/bin/sh
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
. $SCRIPTPATH/clirc-config

if [ $# -gt 0 ]
	then
	msg="$*"
fi

echo "NICK $nick"
echo "USER $nick +i * :$0"

if [ "$WAIT_FOR_NS_BEFORE_JOIN" -eq "0" ]
	then
	sleep 1 # crappy...
 	echo "JOIN #$channel"
fi


while read MESSAGE
do
  case "$MESSAGE" in
    PING*)
      echo "PONG${MESSAGE#PING}"
      ;;
    *registered*)
      echo "PRIVMSG NickServ :identify $password"
      ;;
    *identified*)
      echo "JOIN #$channel"
      ;;
    *"MODE #$channel +v $nick"*)
      echo "PRIVMSG #$channel :${msg}"
      echo "QUIT"
      ;;
    *)
      ;;
  esac
done

exit 1
