#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
. $SCRIPTPATH/clirc-config

SUBSCRIPT=$SCRIPTPATH/clirc-shell
if [ $# -gt 0 ]
	then
	SUBSCRIPT="$SUBSCRIPT \"$*\""
	echo $*
	echo "$*"
	echo $SUBSCRIPT
	echo "$SUBSCRIPT"
fi

TYPE=TCP4
if [ "$SSL" -eq "1" ]
	then
	TYPE=OPENSSL
fi

socat -v $TYPE:$SERVER:$PORT EXEC:"$SUBSCRIPT"
