#!/bin/sh
source ./clirc-config

if [ $# -gt 0 ]
	then
	msg=$*
fi

echo "NICK $nick"
echo "USER $nick +i * :$0"

while read MESSAGE
do
  case "$MESSAGE" in
    PING*)
      echo "PONG${MESSAGE#PING}"
      ;;
    *registered*)
      echo "PRIVMSG NickServ :identify $password"
      ;;
    *identified*)
      echo "JOIN #$channel"
      ;;
    *"MODE #$channel +v $nick"*)
      echo "PRIVMSG #$channel :${msg}"
      echo "QUIT"
      ;;
    *)
      ;;
  esac
done

exit 1
