#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")


SUBSCRIPT=$SCRIPTPATH/clirc-shell
SERVER=irc.freenode.net
PORT=6667


socat -v TCP4:$SERVER:$PORT EXEC:$SUBSCRIPT

