#!/bin/sh

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

subscript=$SCRIPTPATH/clirc-shell
server=irc.freenode.net
port=6667

socat -v TCP4:$server:$port EXEC:$subscript

